apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wpo55epvf-go
  janus-idp.io/tekton: wpo55epvf-go
  backstage.io/kubernetes-id: wpo55epvf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wpo55epvf-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
